### ISSUE TITLE
Gradle with Configuration Cache

### ISSUE THREAD

**Issue by Komdosh** [mygrocerydeals/gradle-s3-plugin#8]
I use Gradle with Kotlin DSL. Everything worked fine until I tried to turn on the [Gradle Configuration Cache](https://docs.gradle.org/current/userguide/configuration_cache.html).

```Kotlin
  plugins {
      id("com.github.node-gradle.node") apply true
      id("com.mgd.core.gradle.s3") version "1.3.1" apply true
  }
  ...
   s3 {
          region = "us-east-1"
          bucket = "s3ArtifactFolder"
      }
  ...
    tasks.register("uploadArtifactToS3", S3Upload::class) {
        keyPrefix = "myS3Dir"
        sourceDir = "aritfactAbsolutePath"
    }
```
Error:
```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 's3' for project ':uploadArtifactToS3' of type org.gradle.api.Project.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
	at org.gradle.api.internal.project.DefaultDynamicLookupRoutine.property(DefaultDynamicLookupRoutine.java:31)
	at org.gradle.api.internal.project.DefaultProject.property(DefaultProject.java:1158)
	at org.gradle.api.internal.project.DefaultProject.getProperty(DefaultProject.java:1135)
	at com.mgd.core.gradle.AbstractS3Task.getProfile(AbstractS3Task.groovy:34)
	at com.mgd.core.gradle.S3Upload_Decorated.getProfile(Unknown Source)
```

How to fix this?

**Comment by Komdosh** [comment]
It appears that there is an issue with the task extension (com.mgd.core.gradle.S3Extension). Gradle does not have access to the project's configuration cache when executing the task.

https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:task_extensions

**Comment by peter-thomas-mgd** [comment]
@Komdosh Sorry this is not working for you. Unfortunately, this plugin was built before the Configuration Cache was introduced and the way the code is currently written will not work with the Configuration Cache enabled.
The plugin uses an extension to access values registered at the project level to configure the default values common to all s3 tasks. Unfortunately, this is not supported with the Configuration Cache enable, and the code will need to be refactored to work correctly in this case. The plugin has never been tested to work correctly with the Configuration Cache enabled, so this limitation was not foreseen.
So the short answer - for now - is that you will not be able to use this plugin with this feature turned on. It will take a bit of time and effort to rework the code to play nicer when the Configuration Cache is enabled. I will see what can be done in the short term to implement a workaround over the next few days.

**Comment by peter-thomas-mgd** [comment]
Please see version `1.3.2` of the plugin, which no longer throws exceptions when the Configuration Cache is enabled. Let me know if you continue to experience issues.

**Comment by Komdosh** [comment]
Thank you! It works!
